### ISSUE TITLE
Dnt use this 

### ISSUE THREAD

**Issue by anky2901** [gellmoxer/whats#2]
I lost all my data after using this 
All files extensions got renamed to GellMoxer and nothing usable now 😢 
I lost my most important 
But developers dnt even care 
Dnt fall in these traps and dnt use this

**Comment by gellmoxer** [comment]
@anky2901 Comment/add your tele nmber here

**Comment by anky2901** [comment]
Telegram info 
@Mentalmax is my user and the name will be ACE anky
